### ISSUE TITLE
ReaImGui 0.7 error

### ISSUE THREAD

**Issue by s0u7h** [ReaCoMa/ReaCoMa-2.0#10]
The scripts are failing with an integer error on the latest version of ReaImGui 0.7. Working on rollback to 0.62

According to cfillion's post here https://forum.cockos.com/showpost.php?p=2571339&postcount=527,  scripts developed under older ReaImGUI need the following compatibility shim added:
```
dofile(reaper.GetResourcePath() .. '/Scripts/ReaTeam Extensions/API/imgui.lua')
  ('0.6')
```

(EDIT - tried this at the top of imgui_helpers.lua and it seems to work with ReaImGui 0.7 installed via ReaPack)

Thanks for making and sharing these awesome scripts, just discovered ReaCoMa and it looks phenomenal.

**Comment by jamesb93** [comment]
Thanks for this! Seems an easy update. Should be able to accomodate a fix quite quickly on the main branch

**Comment by jamesb93** [comment]
I've updated it to work with 0.7 from version 2.2.0 onwards now.

Either `git clone` and `pull` the main branch or you can grab the latest release from here:

https://github.com/ReaCoMa/ReaCoMa-2.0/releases/tag/2.2.0a

**Comment by s0u7h** [comment]
Thanks, it works wonderfully now! Looking forward to exploring this.
