### ISSUE TITLE
there is no such realmgui via the reapack manage repositories

### ISSUE THREAD

**Issue by sonnyobrien** [ReaCoMa/ReaCoMa-2.0#14]
![image](https://user-images.githubusercontent.com/27340727/197169419-613c5275-ef0c-4f05-8a32-064ea68bf9e2.png)

The tutorial guide says to search for this but no such thing exists.

**Comment by jamesb93** [comment]
Make sure that under "Manage Repositories" you have the Extensions package enabled.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/13281862/197339707-01526373-553f-4461-a48d-05d1611ce0a9.png">

<img width="634" alt="image" src="https://user-images.githubusercontent.com/13281862/197339724-1d4079e0-96d3-4821-9488-bf271a63cb60.png">

Then synchronise your packages.
