### ISSUE TITLE
ampslice.lua:22: 'for' limit must be a number

### ISSUE THREAD

**Issue by g-stavridis** [ReaCoMa/ReaCoMa-2.0#16]
Hi, thank you for making ReaCoMa!

After updating to ReaCoMa v2.0, Reaper v6.71 and ReaPack v1.2.4.2 I get the following errors when trying to segment audio with TransientSlice, AmpSlice and AmpGate:

transientslice.lua:22: 'for' limit must be a number
ampslice.lua:22: 'for' limit must be a number
ampgate.lua:24: 'for' limit must be a number

Am I missing something? : )

**Comment by jamesb93** [comment]
Not sure... I will have a look into this. Do you have all the dependencies installed?

**Comment by lionelthek** [comment]
Yes I have exactly the same problem…and all the dependencies are installed…I think so

**Comment by jamesb93** [comment]
Will have a fix for the issue tonight @lionelthek and @g-stavridis

**Comment by jamesb93** [comment]
Fixed here: https://github.com/ReaCoMa/ReaCoMa-2.0/releases/tag/2.7.0

**Comment by lionelthek** [comment]
THANKS !! 
Everything works fine !!
Happy new year 

Lionel
