### ISSUE TITLE
NMF Cross error

### ISSUE THREAD

**Issue by ricknance** [ReaCoMa/ReaCoMa-2.0#17]
I'm getting about a 50% fail rate on using this. Sometimes it clears up if I restart the computer

ImGUI message:

(g.CurrentWindowStack.Size == 1) && "Mismatched Begin/BeginChild vs End/EndChild calls: did you forget to call End/EndChild?

Console message:
/Volumes/SamsungX5/Jan-2023/ebenezer swamp/22Jan/paper carbon corpus/audio/Rick DryIce_nmfcross_167448705492371.wav failed to be made by the command line.
stack traceback:
	...ication Support/REAPER/Scripts/ReaCoMa 2.0/lib/utils.lua:122: in function 'utils.assert'
	...cation Support/REAPER/Scripts/ReaCoMa 2.0/lib/layers.lua:21: in function 'layers.matrix_output_exists'
	...t/REAPER/Scripts/ReaCoMa 2.0/lib/algorithms/nmfcross.lua:38: in function 'algorithms/nmfcross.perform_update'
	...Support/REAPER/Scripts/ReaCoMa 2.0/lib/imgui_helpers.lua:92: in function 'imgui_helpers.process'
	...Support/REAPER/Scripts/ReaCoMa 2.0/lib/imgui_wrapper.lua:31: in function 'imgui_wrapper.loop'
	...Support/REAPER/Scripts/ReaCoMa 2.0/lib/imgui_wrapper.lua:107: in function <...Support/REAPER/Scripts/ReaCoMa 2.0/lib/imgui_wrapper.lua:106>

**Comment by jamesb93** [comment]
Would oyu be able to send me the input file and the settings that you are using to process it?

**Comment by ricknance** [comment]
After the last freeze/restart everything is going well. I will record the
settings and file information and send it with the console report if it
happens again.

Thanks James

**Comment by jamesb93** [comment]
Sometimes if the process is quite processing power intensive it can take a while to finish and for whatever reason the command line doesn't report back to the ReaScript wrapper what it did properly. Sometimes it also just times out and fails, though that should be accounted for. Anyway, I will leave this ticket open so you can report back any further information as its likely I've done something to create the issue that can be resolved :)

**Comment by jamesb93** [comment]
You might've been experiencing the bug from #20 which I've now fixed. Try this release:

https://github.com/ReaCoMa/ReaCoMa-2.0/releases/tag/2.9.0

**Comment by ricknance** [comment]
Thanks. There actually haven't been any issues since then, but I've tried
smaller sets since then as you kind of suggested.

r

Again, I really appreciate these processes. Nothing else like them.

r
