### ISSUE TITLE
utils.lua:124: Fatal ReaCoMa error

### ISSUE THREAD

**Issue by EVS90** [ReaCoMa/ReaCoMa-2.0#18]
Hi James, 
Thanks for these amazing scripts, I´ve used them on other pc´s than my own, but with my own it doesn´t work.
I used the automatic installation Script to install ReaCoMa 2.0 but i get this always:
...AppData\Roaming\REAPER\Scripts\ReaCoMa 2.0\lib/utils.lua:124: Fatal ReaCoMa error! 

And then in the console:
Learning Reaper\Johann Sebastian Bach - Chaconne, Partita No. 2 BWV 1004 ｜ Hilary Hahn.wav229406037624-1fs.csv could not be read because it does not exist.
stack traceback:
	...AppData\Roaming\REAPER\Scripts\ReaCoMa 2.0\lib/utils.lua:122: in function 'utils.assert'
	...AppData\Roaming\REAPER\Scripts\ReaCoMa 2.0\lib/utils.lua:252: in function 'utils.readfile'
	...REAPER\Scripts\ReaCoMa 2.0\lib/algorithms/onsetslice.lua:43: in function 'algorithms/onsetslice.perform_update'
	...Roaming\REAPER\Scripts\ReaCoMa 2.0\lib/imgui_helpers.lua:94: in function 'imgui_helpers.process'
	...Roaming\REAPER\Scripts\ReaCoMa 2.0\lib/imgui_wrapper.lua:31: in function 'imgui_wrapper.loop'
	...Roaming\REAPER\Scripts\ReaCoMa 2.0\lib/imgui_wrapper.lua:110: in function <...Roaming\REAPER\Scripts\ReaCoMa 2.0\lib/imgui_wrapper.lua:109>

Do you maybe know what´s wrong? Or what i did wrong?

All Best Emil

**Comment by jamesb93** [comment]
Hey Emil,

Do any of the other scripts work?

**Comment by EVS90** [comment]
Hi James, Now im embarrassed , cuz now it works perfectly, I just rebootet my computer.
Really enjoying it!

**Comment by jamesb93** [comment]
No worries :) no matter how, a solved bug is still solved!
