### ISSUE TITLE
Scripting Error

### ISSUE THREAD

**Issue by MartinDDrum** [ReaCoMa/ReaCoMa-2.0#19]
Hello,

I am new to using ReaCoMa (and I'm working on a PC)
I'm trying to slice up a track that is 30 minutes long and I receive the following messages when I ask to see the preview for the ampslice

...ta\Roaming\REAPER\Scripts\ReaCoMa-2.0-main\lib/utils.lua:124: Fatal ReaCoMa error! An assertion has failed. Refer to the console for more information. If you provide a bug report it is useful to include the output of this window and the console.

Here is the console output.
D:\Users\marti\Desktop\CDMGrooveBank\CelesteMarc\Celeste.wav43146843321-1fs.csv could not be read because it does not exist.
stack traceback:
	...ta\Roaming\REAPER\Scripts\ReaCoMa-2.0-main\lib/utils.lua:122: in function 'utils.assert'
	...ta\Roaming\REAPER\Scripts\ReaCoMa-2.0-main\lib/utils.lua:252: in function 'utils.readfile'
	...PER\Scripts\ReaCoMa-2.0-main\lib/algorithms/ampslice.lua:45: in function 'algorithms/ampslice.perform_update'
	(...tail calls...)
	...ng\REAPER\Scripts\ReaCoMa-2.0-main\lib/imgui_wrapper.lua:59: in function 'imgui_wrapper.loop'
	...ng\REAPER\Scripts\ReaCoMa-2.0-main\lib/imgui_wrapper.lua:110: in function <...ng\REAPER\Scripts\ReaCoMa-2.0-main\lib/imgui_wrapper.lua:109>

Also, is it possible that when launching it on windows that it does not ask you to find the location for the binaries? I had to move the binaries to the ReaCoMa folder because I could not see this prompt - perhaps something to add in the installation guide. (perhaps it is only suggested once and I clicked out of it and from that moment it resulted to its defult bin location)

thanks,
M
![Screenshot 2023-02-06 101523](https://user-images.githubusercontent.com/124596627/217009953-17f18044-be88-4dbd-bbd2-bb36a0db8930.png)

**Comment by jamesb93** [comment]
How did you do the installation? Was it automatic via the script or by downloading here from GitHub?

Since a few versions ago I enforce that the bin folder be located _inside_ the ReaCoMa folder, unless specified in the config.lua file.

**Comment by MartinDDrum** [comment]
I downloaded it from GitHub and followed the steps from the Wiki. Moving my FluCoMa binaries to the /recoma/bins allowed reaper to find it all. I can see the UI and it all works until I try to see the preview.

Thanks!

**Comment by jamesb93** [comment]
Awesome :) Glad you got it working.
