### ISSUE TITLE
Nmfcroos and audiotransport not working 

### ISSUE THREAD

**Issue by melvidodream** [ReaCoMa/ReaCoMa-2.0#20]
Hello! 
I'm not an expert in using scripts in reaper but I test the flucoma toolkit a bit in max but I don't understand why nmfcross and audiotransport don't work. 
I tried to create two tracks with two different audio files and a third empty or use three audio track with the third one has a silent audio file but nothing. 
I'll post a screenshoot with the problem. 

Thank you so much for all your incredible work @jamesb93! 

<img width="951" alt="Schermata 2023-04-02 alle 18 03 34" src="https://user-images.githubusercontent.com/100131677/229361389-b41ee2dd-7d23-4e59-afd7-eda5be1cd173.png">

<img width="916" alt="image" src="https://user-images.githubusercontent.com/100131677/229361417-8ef97f74-440b-45bb-a29c-7d8a6841d79c.png">

**Comment by jamesb93** [comment]
Which version are you using? Are you on the absolute latest version?

**Comment by melvidodream** [comment]
Yes, the last one. I don't know if it can help, but I'm using also using reaper v.6.77

**Comment by jamesb93** [comment]
Can you send me the sound files you are trying to process?

**Comment by jamesb93** [comment]
I can reproduce here! Looking into it :)

**Comment by melvidodream** [comment]
Thank you so much! 
Hope it didn't bother you much! <3

**Comment by jamesb93** [comment]
Done!

https://github.com/ReaCoMa/ReaCoMa-2.0/releases/tag/2.9.0

No trouble at all. Thank you for filing a bug :) Let me know if this works for you.

**Comment by melvidodream** [comment]
@jamesb93 All working, thanks!
