### ISSUE TITLE
Reacoma 2.0 assertion error

### ISSUE THREAD

**Issue by LFSaw** [ReaCoMa/ReaCoMa-2.0#4]
I tried (and managed) to install reacoma on my M1 machine, first manually, then with the automated way , however, when trying to run any of the scripts, I get the two errors:

in ReaScript console output:

```
ImGui assertion failed: (q.CurrentWindowStack.Size
1) && "Mismatched Begin/BeginChild vs End/EndChild
calls: did you forget to call End/EndChild?
```

in ReaScript Error

```
...erma/vol/dev/sound/src/ReaCoMa-2.0/lib/imgui_wrapper.lua:48: ImGui_InputText: ImGui assertion failed: id != window->ID && "Cannot have an empty ID at the root of a window. If you need an empty label, use ## and read the FAQ about how the ID Stack works!"
```
this is independent of running the scripts in the manual install or the automated one…

any help would be much appreciated!

I tested ImGUI with the basic examples I found [here](https://forums.cockos.com/showthread.php?t=250419) and that example works.

My system setup:

+ Mac OS 12.3.1 (21E258)
+ REAPER v6.53/OSX64-clang rev 3923c1 (Mar 29 2022)

cheers and thanks for all the great work you out into this already!

**Comment by jamesb93** [comment]
I've had a deeper look into this and I'm finding it difficult to recreate the issue. We are using the same build version of REAPER (except mine is arm64 not OSX64) and the same version of Mac OS. The missing piece is your version of ReaImGui which may be causing the issue.

The dynamic library for the GUI bindings are found here on Mac OS:

`~/Library/Application Support/REAPER/UserPlugins`

Can you delete whatever is there following the naming convention of:

`reaper_imgui-*.dylib`

and replace with this version:

https://github.com/cfillion/reaimgui/releases/download/v0.6.1/reaper_imgui-x86_64.dylib

If that doesn't work we can dig deeper.

**Comment by LFSaw** [comment]
hello :)

I managed to get it to work:

it was an old path to  the `ReaCoMa-2.0/bin` directory in `reaper-extstate.ini` I seem to have copied over when moving my reaper config from an old machine. 
Removing the whole `[reacoma]` section in there now makes the system work. Thanks for your efforts, though!

**Comment by jamesb93** [comment]
I'm just glad it is working :)

Good to know about this sort of thing though, perhaps I can make some more intelligent assumptions about the extstate that I set.

Thanks for reporting the issue and let me know if I can help any more!
